openapi: 3.0.0
info:
  title: Project-1 APIs
  description: Explore the API endpoints for Project-1, featuring demonstration examples to help guide you through their usage, all built according to OpenAPI v3 specifications.
  version: 1.0.0

tags:
  - name: Project-1-apis
    description: API endpoints for using Project-1
    x-displayName: Project-1 APIs

x-tagGroups:
  - name: Project-1 APIs
    tags:
      - Project-1-apis

paths:
  /all_models:
    get:
      summary: List all Models
      tags:
        - Project-1 APIs
      parameters:
        - name: user_id
          in: query
          description: The ID of the user making the request
          required: true
          schema:
            type: string
        - name: application_id
          in: query
          description: The ID of the application making the request
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of all the available models
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    model_id:
                      type: string
                      description: The ID of the model
                    model_name:
                      type: string
                      description: The name of the model
                  required:
                    - model_id
                    - model_name

  /get_model:
    get:
      summary: Single model info
      tags:
        - Project-1 APIs
      parameters:
        - name: model_id
          in: query
          description: The ID of the application making the request
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Information of the given model will be available
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    model_id:
                      type: string
                      description: The ID of the model
                    model_name:
                      type: string
                      description: The name of the model
                    model_size:
                      type: string
                      description: The name of the model
                    model_description:
                      type: string
                      description: The name of the model
                  required:
                    - model_id
                    - model_name
                    - model_size
